// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH1A3AjD52Wijthv9mTvEA433AA-t4wU8',
    appId: '1:85813360425:web:24faf827fb8a5b20ba2938',
    messagingSenderId: '85813360425',
    projectId: 'project-jr-2d2b6',
    authDomain: 'project-jr-2d2b6.firebaseapp.com',
    storageBucket: 'project-jr-2d2b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkdtBKEsGVzofHasyqS0fKXIW0CxGo5AI',
    appId: '1:85813360425:android:8ab99e929f0b75baba2938',
    messagingSenderId: '85813360425',
    projectId: 'project-jr-2d2b6',
    storageBucket: 'project-jr-2d2b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPa2WTaHPYifhID28FGkFP72-39tkqJg',
    appId: '1:85813360425:ios:0f4a66cea8ef9ba0ba2938',
    messagingSenderId: '85813360425',
    projectId: 'project-jr-2d2b6',
    storageBucket: 'project-jr-2d2b6.firebasestorage.app',
    iosBundleId: 'com.example.jr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPa2WTaHPYifhID28FGkFP72-39tkqJg',
    appId: '1:85813360425:ios:0f4a66cea8ef9ba0ba2938',
    messagingSenderId: '85813360425',
    projectId: 'project-jr-2d2b6',
    storageBucket: 'project-jr-2d2b6.firebasestorage.app',
    iosBundleId: 'com.example.jr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH1A3AjD52Wijthv9mTvEA433AA-t4wU8',
    appId: '1:85813360425:web:caf1c8895ae68beeba2938',
    messagingSenderId: '85813360425',
    projectId: 'project-jr-2d2b6',
    authDomain: 'project-jr-2d2b6.firebaseapp.com',
    storageBucket: 'project-jr-2d2b6.firebasestorage.app',
  );
}
